# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - "3306:3306"


#Run docker in detached mode
#docker-compose up -d
#docker-compose run --service-ports db
